#!/bin/sh

echo "Checking changed files to see if there are errors..."
#grab all JavaScript and TypeScript files that have changed
changedFiles=$(git diff --staged --name-only|grep -E "\.(js|ts)$")

#run eslint against all changed JavaScript files
if [ ! -z "$changedFiles" ]
then
resultLint=$(eslint --ext .js,.ts $changedFiles)
echo "we get here"
fi

#run typescript
resultCheckTypes=$(npm run --silent check-types)

#concatenate the results
resultsCombined='=====ESLint=====\n${resultLint}\n=====TypeScript=====\n${resultCheckTypes}'

#look for the word 'error' in the results
case $resultsCombined in
    *error*)
        echo "$resultsCombined"
        echo
        echo "Changes could not be committed due to errors found by ESLint and/or TypeScript. Please correct these before committing."
        exit 1
        ;;
    *)
        echo "ESLint and TypeScript have found no errors in the committed files."
        ;;
    esac