#!/bin/sh

echo "Checking changed files to see if there are errors..."
#grab all Javascript files that have changed
changedFiles=$(git diff --staged --name-only|grep "\.js$")

#run eslint against all changed Javascript files
if [$? == 0] then
result=$(eslint $changedFiles)
fi

#look for the word 'error' in the results
case $result in
    *error*)
        echo "$result"
        echo
        echo "Changes could not be committed due to errors found by ESLint. Please correct these before committing."
        exit 1
        ;;
    *)
        echo "ESLint has found no errors in the committed Javascript files."
        ;;
    esac