#!/bin/sh

echo "Checking changed files to see if there are errors..."
#grab all JavaScript and TypeScript files that have changed
changedFiles=$(git diff --staged --name-only|grep -E "\.(js|ts)$")

#run eslint against all changed JavaScript files
if [ ! -z "$changedFiles"]
then
resultLint=$(eslint --ext .js,.ts $changedFiles)
echo "we get here"
fi

#look for the word 'error' in the results
case $resultLint in
    *error*)
        echo "$resultLint"
        echo
        echo "Changes could not be committed due to errors found by ESLint. Please correct these before committing."
        ;;
    *)
        echo "ESLint has found no errors in the committed files."
        ;;
    esac

#run typescript
resultCheckTypes =$(npm run --silent check-types)

case $resultCheckTypes in
    *error*)
        echo "$resultCheckTypes"|grep "error"
        echo
        echo "Changes could not be committed due to errors found by TypeScript. Please correct these before committing."
        exit 1
        ;;
    *)
        echo "TypeScript has found no errors in all .ts files."
        ;;
    esac